### PR TITLE
fixed pegination link bug

### LINKED ISSUE #101: Pagination links get funky when reaching triple digits
## Summary of Bug

:eyes_bleeding:
Screen Shot 2021-06-04 at 1 59 59 PM

## Version

current

## Steps to Reproduce

1. Find a table with a lot of data and click through till you get to 100.
1. Behold the glory of overlapping links.

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by Shomy032**
I fixed pegination links bug , when numbers get over 99 they stack to close to each other .

closes #101

### CODE REVIEW

File: src/Components/Pagination/PaginationListItem.js [hunk 1]
```diff
@@ -1,20 +1,24 @@
...
+  background-color: ${({ secondary, theme, active }) =>
+    !secondary && active ? theme.BACKGROUND_THEME : 'inherit'};
   > button {
     color: ${({ theme }) => theme.FONT_PRIMARY};
   }
   + li {
-    margin-left: -2px;
+    margin-left: 3.5px;
+    margin-right: 3.5px;
   }
```
Comment (webbushka) [inline src/Components/Pagination/PaginationListItem.js:22]: Don't add the extra selector, just put this margin prop up under the main selector.

Can shorthand this as well `margin: 0 4px;`

**Review by webbushka — APPROVED** [review]
Thank you!
